name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Passo 1: Adicionado para diagnosticar o problema de timeout
      - name: Test Network Connectivity
        run: curl -v https://www.saucedemo.com/

      # Passo 2: Usando a action oficial do Cypress para simplificar e otimizar
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          # Se seus testes não estiverem na raiz, especifique o diretório
          # working-directory: path/to/project